name = "AdversarialAttacks"
uuid = "0930d2b9-30a9-4ff9-b124-6eb7688acdd1"
authors = ["Orestis Papandreou <orestis.papandreou@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DecisionTree = "0.12.4"
Flux = "0.16.7"
OneHotArrays = "0.2.10"
Random = "1.11.0"
julia = "1.11"
