name = "AdversarialAttacks"
uuid = "0930d2b9-30a9-4ff9-b124-6eb7688acdd1"
authors = ["Orestis Papandreou <orestis.papandreou@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"

[compat]
Flux = "0.16.7"
MLDatasets = "0.7.20"
julia = "1.11"
