name = "AdversarialAttacks"
uuid = "0930d2b9-30a9-4ff9-b124-6eb7688acdd1"
authors = ["Orestis Papandreou <orestis.papandreou@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Flux = "0.16.7"
Random = "1.11.0"
julia = "1.11"
