[deps]
AdversarialAttacks = "0930d2b9-30a9-4ff9-b124-6eb7688acdd1"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
